<?php

/*
 * Typed copy of the faker_mixin.php that xefi/faker-php-laravel regenerates on
 * every composer install. Kept here so the generated file stays untouched.
 */

namespace Xefi\Faker\Container;

/**
 * @method array<int, string> wordsAsArray(int $words = 3)
 * @method string words(int $words = 3)
 * @method array<int, string> sentencesAsArray(int $sentences = 3)
 * @method string sentences(int $sentences = 3)
 * @method array<int, string> paragraphsAsArray(int $paragraphs = 3)
 * @method string paragraphs(int $paragraphs = 3)
 * @method ?string getLocale()
 * @method int digit()
 * @method int number(int $min, int $max)
 * @method float float(float $min, float $max, int $decimals = 1)
 * @method mixed letter()
 * @method array<array-key, mixed>|string shuffle(array<array-key, mixed>|string $needle)
 * @method string shuffleString(string $needle)
 * @method array<array-key, mixed> shuffleArray(array<array-key, mixed> $needle)
 * @method string convertCharacters(string $string)
 * @method string semver()
 * @method string emoji()
 * @method string uuid()
 * @method string ulid()
 * @method string md5()
 * @method string sha1()
 * @method string sha256()
 * @method string sha512()
 * @method \DateTime dateTime(\DateTimeInterface|string|int $fromTimestamp = '-30 years', \DateTimeInterface|string|int $toTimestamp = 'now')
 * @method \DateTimeImmutable dateTimeImmutable(\DateTimeInterface|string|int $fromTimestamp = '-30 years', \DateTimeInterface|string|int $toTimestamp = 'now')
 * @method int timestamp(\DateTimeInterface|string|int $fromTimestamp = '-30 years', \DateTimeInterface|string|int $toTimestamp = 'now')
 * @method string timezone()
 * @method string sdl()
 * @method string tld()
 * @method string domain()
 * @method string ip()
 * @method string ipv4()
 * @method string ipv6()
 * @method mixed macAddress()
 * @method mixed email()
 * @method string url(mixed $secure = true)
 * @method string safeColorName()
 * @method string colorName()
 * @method string safeHexColor()
 * @method string hexColor()
 * @method array<int, int> rgbColorAsArray()
 * @method string rgbColor()
 * @method string rgbCssColor()
 * @method array<int, int|float> rgbaColorAsArray()
 * @method string rgbaColor()
 * @method string rgbaCssColor()
 * @method array<int, int|float> hslColorAsArray()
 * @method string hslColor()
 * @method string hslCssColor()
 * @method array<int, int|float> hslaColorAsArray()
 * @method string hslaColor()
 * @method string hslaCssColor()
 * @method string name(?string $gender = null)
 * @method string firstName(?string $gender = null)
 * @method string lastName()
 * @method mixed title(?string $gender = null)
 * @method string iban(?string $countryCode = null, ?string $format = null)
 * @method mixed boolean(int $percentage = 50)
 * @method mixed randomElement(array<array-key, mixed> $array)
 * @method mixed randomKey(array<array-key, mixed> $array)
 * @method string phoneNumber(?string $format = null, string $separator = '', ?string $prefix = null)
 * @method string indicatoredPhoneNumber(?string $format = null, string $separator = '')
 * @method string spacedPhoneNumber(?string $format = null, ?string $prefix = null)
 * @method string spacedIndicatoredPhoneNumber(?string $format = null)
 * @method string dottedPhoneNumber(?string $format = null, ?string $prefix = null)
 * @method string dottedIndicatoredPhoneNumber(?string $format = null)
 * @method string dashedPhoneNumber(?string $format = null, ?string $prefix = null)
 * @method string dashedIndicatoredPhoneNumber(?string $format = null)
 * @method string cellPhoneNumber(string $separator = '', ?string $prefix = null)
 * @method string indicatoredCellPhoneNumber(string $separator = '')
 * @method string spacedCellPhoneNumber(?string $prefix = null)
 * @method string spacedIndicatoredCellPhoneNumber()
 * @method string dottedCellPhoneNumber(?string $prefix = null)
 * @method string dottedIndicatoredCellPhoneNumber()
 * @method string dashedCellPhoneNumber(?string $prefix = null)
 * @method string dashedIndicatoredCellPhoneNumber()
 * @method string landlinePhoneNumber(string $separator = '', ?string $prefix = null)
 * @method string indicatoredLandlinePhoneNumber(string $separator = '')
 * @method string spacedLandlinePhoneNumber(?string $prefix = null)
 * @method string spacedIndicatoredLandlinePhoneNumber()
 * @method string dottedLandlinePhoneNumber(?string $prefix = null)
 * @method string dottedIndicatoredLandlinePhoneNumber()
 * @method string dashedLandlinePhoneNumber(?string $prefix = null)
 * @method string dashedIndicatoredLandlinePhoneNumber()
 * @method string geoLocation()
 * @method float latitude()
 * @method float longitude()
 */
class Container {}
